apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: bookinfo-lab
spec:
  hosts:
  - reviews
  http:
  - match:
    - headers:
        user-agent:
          regex:  .*Firefox.*
    route:
    - destination:
        host: reviews
        subset: v1
  - route:
    - destination:
        host: reviews
        subset: v1
      weight: 0
    - destination:
        host: reviews
        subset: v2
      weight: 0
    - destination:
        host: reviews
        subset: v3
      weight: 100
    #mirror:
    #  host: reviews
    #  subset: v3